version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: make create release script executable
          command: chmod +x create_release.sh
      - run:
          name: create release
          command: ./create_release.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
